# -*- coding: utf-8 -*-
"""avcid1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HTpr6t-0cXg4Jb-Pcdrn72obprG2yCws
"""

import pandas as pd

df = pd.read_csv('/content/diabetes.csv')

df.head()

df.columns

"""df.dtypes"""

df.info()

df.describe()

df.duplicated().sum()

from google.colab import drive
drive.mount('/content/drive')

df['Age'].unique()

df['Glucose']

df[['Glucose','Age','BMI']]

df[(df['Age']>50)]

#chack invalid Zero  value
(df[['Glucose','BloodPressure','SkinThickness','Insulin','BMI']]==0).sum()

