# -*- coding: utf-8 -*-
"""Lecture1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19jdBtKN-OGDg8-zQjrT0XqikqNeNYg5l
"""

print("Hello world")

"""print("Addition",2+3)"""

a=5
b=8
print(a-b)
print(a+b)

s=a+b
print(s)

s=int(input("Enter any Number : "))
p=int(input("Enter second Number :"))
a=s+p
print("Sum of digit : ",a)

a=int(input("Enter any Number :"))
b=int(input("Enter second Number :"))
c=int(input("Enter third Number :"))
d=a+b
e=a*c
g=a/b
f=b/c
h=b*c
print("Sum of digit :",d)
print("Mult. of digit :",e)
print("Divi. of digit :",g)
print("Divi. of digit :",f)
print("Mult. of digit :",h)

a=50
b=25
print("before swapping :",a,b)
a,b=b,a
print("After swapping : ",a,b)

#Assigment operators
a=3
b=2
print(a>b)
print(a<b)
print(a>=b)
print(a<=b)
print(a==b)
print(a!=b)

# logical operators
a=20
b=20
print(a is b)
print(a is not b)
print(id(a))
print(id(b))

#membership operator
#in
#not
x=["apple","Banana"]
print("banana"in x)
print("banana" not in  x)

#using else
a=int(input("Enter any Number :"))
if a>=18:
  print("You are eligible to vote")
else:
  print("You are not eligible to vote")

#print grading system
marks = int(input("Enter any number : "))
if marks>=90:
  print("Grad A")
if marks<=80:
  print("Grad B")
else:
  print("C")

#for loop
x=range(5)
for i in  x:
  print(i)

x=("GLA UNIVERSITY")
for  i in x:
  print(i)

#whiel loop
i=1
while i<6:
  print(i)
  i+=1

#printing table
n=int(input("Enter any number : "))
i=1
while i<=10:
  print(f"{n} X {i} = {n*i}")
  i+=1

#String
name =("GLA UNIVERSITY")
print(name[0])
print(name[1])
print(name[0:3])
print(name[-1])
print(name[4])
print(name[-5:-1])
print(name[6])

#data structure in pythan
#list
#tuple
#dictionary
#set

#list
list=["kapil",21,"kumar","mathura",5.10,21]
print(list)
print(len(list))

print(list[3])

list.append("hello")
print(list)

list.insert(2,"B.tech")
print(list)

#tuple
a={1,2,3,4,5}
b={4,5,6,7,8}
print(a.difference(b))
print(a.union(b))
print(a.intersection(b))