# -*- coding: utf-8 -*-
"""Lecture3ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wvnTzHu-woifmoC8svzl9UOZ8VndeCnX
"""

import numpy as np

# 1D array
arr = np.array({10,20,30,40})
print(arr)

# 2D array
arr = np.array([[1,2,3],[4,5,6]])
print(arr)

# 3D array
arr = np.array([[[1,2,3],[4,5,6]],[[5,6,7],[8,9,0]]])
print(arr)

arr = np.array([[1,2,3],[4,5,6]])
print(arr.np)

a=np.array([1,2,3,4])
b=np.zeros((3,4))
c=np.ones((2,3))
d=np.arange(0,20,2)
e=np.linspace(0,10,5)
print(a)
print(b)
print(c)
print(d)
print(e)

# Vectorized Computation
arr = np.array([1,2,3,4,5])
result = arr*2
print(result)

list = (1,2,3,4,5)
result = list*2
print(result)

arr = [1, 2, 3, 4, 5]

result = []

for i in arr:
    result.append(i * 2)

print(result)

arr = np.array([1, 2, 3, 4, 5])
result = arr + 10
print(result)

arr = np.array([1,4,9,16,18])
print(np.sqrt(arr))

arr = np.array([1,2,3,4])
arr2 = np.array([5,6,7,8])
print(np.array_equal(arr,arr2))

arr = np.array([1,2,3,4])
arr2 = np.array([5,6,7,8])
print(np.array(arr+arr2))

arr = np.array([1,2,3,4])
arr2 = np.array([5,6,7,8])
print(np.subtract(arr,arr2))

a = np.array([1,2,3,4])
b = np.array([5,6,7,8])
print(a+b)

a = np.array([1,2,3,4])
b = np.array([5,6,7,8])
print(a+b)
print(a-b)
print(a*b)
print(a/b)

arr = np.array([10,20,30,40])
print(arr > 20)

arr = np.array([10,20,30,40])
passed = arr[arr >= 20]
print(passed)

arr = np.array([10,20,30,40])
print(np.max(arr))
print(np.min(arr))
print(np.mean(arr))
print(np.median(arr))
print(np.std(arr))
print(np.sum(arr))
print(np.sort(arr))
print(np.argsort(arr))

